// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: approvals.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createApproval = `-- name: CreateApproval :one
INSERT INTO approvals (requirement_id, version_number, status_id, comment, approver_id)
VALUES (
    $1, $2,
    (SELECT id FROM approval_statuses WHERE status = 'pending'),
    $3, $4
)
RETURNING id, requirement_id, version_number, status_id, comment, approver_id, created_at
`

type CreateApprovalParams struct {
	RequirementID pgtype.UUID
	VersionNumber int32
	Comment       pgtype.Text
	ApproverID    pgtype.UUID
}

func (q *Queries) CreateApproval(ctx context.Context, arg CreateApprovalParams) (Approval, error) {
	row := q.db.QueryRow(ctx, createApproval,
		arg.RequirementID,
		arg.VersionNumber,
		arg.Comment,
		arg.ApproverID,
	)
	var i Approval
	err := row.Scan(
		&i.ID,
		&i.RequirementID,
		&i.VersionNumber,
		&i.StatusID,
		&i.Comment,
		&i.ApproverID,
		&i.CreatedAt,
	)
	return i, err
}

const getAllApprovals = `-- name: GetAllApprovals :many
SELECT a.id, a.requirement_id, a.version_number, a.comment, a.created_at,
       aps.status,
       r.title       AS requirement_title,
       u.full_name   AS approver_name
FROM approvals a
JOIN approval_statuses aps ON a.status_id      = aps.id
JOIN requirements      r   ON a.requirement_id = r.id
                           AND a.version_number = r.version_number
LEFT JOIN users        u   ON a.approver_id    = u.id
ORDER BY a.created_at DESC
`

type GetAllApprovalsRow struct {
	ID               pgtype.UUID
	RequirementID    pgtype.UUID
	VersionNumber    int32
	Comment          pgtype.Text
	CreatedAt        pgtype.Timestamp
	Status           string
	RequirementTitle string
	ApproverName     pgtype.Text
}

func (q *Queries) GetAllApprovals(ctx context.Context) ([]GetAllApprovalsRow, error) {
	rows, err := q.db.Query(ctx, getAllApprovals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllApprovalsRow
	for rows.Next() {
		var i GetAllApprovalsRow
		if err := rows.Scan(
			&i.ID,
			&i.RequirementID,
			&i.VersionNumber,
			&i.Comment,
			&i.CreatedAt,
			&i.Status,
			&i.RequirementTitle,
			&i.ApproverName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getApprovalsByProjectId = `-- name: GetApprovalsByProjectId :many
SELECT a.id, a.requirement_id, a.version_number, a.comment, a.created_at,
       aps.status,
       r.title     AS requirement_title,
       u.full_name AS approver_name
FROM approvals a
JOIN approval_statuses aps ON a.status_id      = aps.id
JOIN requirements      r   ON a.requirement_id = r.id
                           AND a.version_number = r.version_number
LEFT JOIN users        u   ON a.approver_id    = u.id
WHERE r.project_id = $1
ORDER BY a.created_at DESC
`

type GetApprovalsByProjectIdRow struct {
	ID               pgtype.UUID
	RequirementID    pgtype.UUID
	VersionNumber    int32
	Comment          pgtype.Text
	CreatedAt        pgtype.Timestamp
	Status           string
	RequirementTitle string
	ApproverName     pgtype.Text
}

func (q *Queries) GetApprovalsByProjectId(ctx context.Context, projectID pgtype.UUID) ([]GetApprovalsByProjectIdRow, error) {
	rows, err := q.db.Query(ctx, getApprovalsByProjectId, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetApprovalsByProjectIdRow
	for rows.Next() {
		var i GetApprovalsByProjectIdRow
		if err := rows.Scan(
			&i.ID,
			&i.RequirementID,
			&i.VersionNumber,
			&i.Comment,
			&i.CreatedAt,
			&i.Status,
			&i.RequirementTitle,
			&i.ApproverName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApproval = `-- name: UpdateApproval :one
UPDATE approvals
SET
    status_id   = (SELECT id FROM approval_statuses WHERE status = $1),
    comment     = COALESCE($2,     comment),
    approver_id = COALESCE($3, approver_id)
WHERE requirement_id = $4
  AND version_number = $5
RETURNING id, requirement_id, version_number, status_id, comment, approver_id, created_at
`

type UpdateApprovalParams struct {
	Status        string
	Comment       pgtype.Text
	ApproverID    pgtype.UUID
	RequirementID pgtype.UUID
	VersionNumber int32
}

func (q *Queries) UpdateApproval(ctx context.Context, arg UpdateApprovalParams) (Approval, error) {
	row := q.db.QueryRow(ctx, updateApproval,
		arg.Status,
		arg.Comment,
		arg.ApproverID,
		arg.RequirementID,
		arg.VersionNumber,
	)
	var i Approval
	err := row.Scan(
		&i.ID,
		&i.RequirementID,
		&i.VersionNumber,
		&i.StatusID,
		&i.Comment,
		&i.ApproverID,
		&i.CreatedAt,
	)
	return i, err
}
