// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: change_requests.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createChangeRequest = `-- name: CreateChangeRequest :one
INSERT INTO change_requests (title, description, requester_id, project_id, status_id, priority_id)
VALUES (
    $1, $2, $3, $4,
    (SELECT id FROM change_request_statuses   WHERE status   = 'open'),
    (SELECT id FROM change_request_priorities WHERE priority = $5)
)
RETURNING id, title, description, requester_id, project_id, status_id, priority_id, created_at, resolved_at
`

type CreateChangeRequestParams struct {
	Title       string
	Description pgtype.Text
	RequesterID pgtype.UUID
	ProjectID   pgtype.UUID
	Priority    string
}

func (q *Queries) CreateChangeRequest(ctx context.Context, arg CreateChangeRequestParams) (ChangeRequest, error) {
	row := q.db.QueryRow(ctx, createChangeRequest,
		arg.Title,
		arg.Description,
		arg.RequesterID,
		arg.ProjectID,
		arg.Priority,
	)
	var i ChangeRequest
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.RequesterID,
		&i.ProjectID,
		&i.StatusID,
		&i.PriorityID,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const getAllChangeRequests = `-- name: GetAllChangeRequests :many
SELECT cr.id, cr.title, cr.description, cr.created_at, cr.resolved_at,
       crs.status,
       crp.priority,
       u.full_name AS requester_name,
       p.name      AS project_name
FROM change_requests cr
JOIN change_request_statuses   crs ON cr.status_id   = crs.id
JOIN change_request_priorities crp ON cr.priority_id = crp.id
JOIN users    u ON cr.requester_id = u.id
JOIN projects p ON cr.project_id   = p.id
ORDER BY cr.created_at DESC
`

type GetAllChangeRequestsRow struct {
	ID            pgtype.UUID
	Title         string
	Description   pgtype.Text
	CreatedAt     pgtype.Timestamp
	ResolvedAt    pgtype.Timestamp
	Status        string
	Priority      string
	RequesterName string
	ProjectName   string
}

func (q *Queries) GetAllChangeRequests(ctx context.Context) ([]GetAllChangeRequestsRow, error) {
	rows, err := q.db.Query(ctx, getAllChangeRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllChangeRequestsRow
	for rows.Next() {
		var i GetAllChangeRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.ResolvedAt,
			&i.Status,
			&i.Priority,
			&i.RequesterName,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkRequirementToChangeRequest = `-- name: LinkRequirementToChangeRequest :exec
INSERT INTO change_request_requirements (id, requirement_id, version_number)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type LinkRequirementToChangeRequestParams struct {
	ID            pgtype.UUID
	RequirementID pgtype.UUID
	VersionNumber int32
}

func (q *Queries) LinkRequirementToChangeRequest(ctx context.Context, arg LinkRequirementToChangeRequestParams) error {
	_, err := q.db.Exec(ctx, linkRequirementToChangeRequest, arg.ID, arg.RequirementID, arg.VersionNumber)
	return err
}

const updateChangeRequestStatus = `-- name: UpdateChangeRequestStatus :one
UPDATE change_requests cr
SET
    cr.status_id   = (SELECT id FROM change_request_statuses WHERE status = $2),
    cr.resolved_at = CASE
                    WHEN $2 IN ('approved','rejected','implemented')
                    THEN CURRENT_TIMESTAMP
                    ELSE resolved_at
                  END
WHERE cr.id = $1
RETURNING id, title, description, requester_id, project_id, status_id, priority_id, created_at, resolved_at
`

type UpdateChangeRequestStatusParams struct {
	ID     pgtype.UUID
	Status string
}

func (q *Queries) UpdateChangeRequestStatus(ctx context.Context, arg UpdateChangeRequestStatusParams) (ChangeRequest, error) {
	row := q.db.QueryRow(ctx, updateChangeRequestStatus, arg.ID, arg.Status)
	var i ChangeRequest
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.RequesterID,
		&i.ProjectID,
		&i.StatusID,
		&i.PriorityID,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}
