// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: change_orders.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createChangeOrder = `-- name: CreateChangeOrder :one
INSERT INTO change_orders (ecr_id, title, justification, assigned_to, status_id, effective_date)
VALUES (
    $1, $2, $3, $4,
    (SELECT id FROM change_order_statuses WHERE status = 'draft'),
    $5
)
RETURNING id, ecr_id, title, justification, assigned_to, status_id, effective_date, created_at
`

type CreateChangeOrderParams struct {
	EcrID         pgtype.UUID
	Title         string
	Justification pgtype.Text
	AssignedTo    pgtype.UUID
	EffectiveDate pgtype.Date
}

func (q *Queries) CreateChangeOrder(ctx context.Context, arg CreateChangeOrderParams) (ChangeOrder, error) {
	row := q.db.QueryRow(ctx, createChangeOrder,
		arg.EcrID,
		arg.Title,
		arg.Justification,
		arg.AssignedTo,
		arg.EffectiveDate,
	)
	var i ChangeOrder
	err := row.Scan(
		&i.ID,
		&i.EcrID,
		&i.Title,
		&i.Justification,
		&i.AssignedTo,
		&i.StatusID,
		&i.EffectiveDate,
		&i.CreatedAt,
	)
	return i, err
}

const createEcoRequirementLink = `-- name: CreateEcoRequirementLink :exec
INSERT INTO eco_requirement_links (id, requirement_id, old_version, new_version)
VALUES ($1, $2, $3, $4)
`

type CreateEcoRequirementLinkParams struct {
	ID            pgtype.UUID
	RequirementID pgtype.UUID
	OldVersion    int32
	NewVersion    int32
}

func (q *Queries) CreateEcoRequirementLink(ctx context.Context, arg CreateEcoRequirementLinkParams) error {
	_, err := q.db.Exec(ctx, createEcoRequirementLink,
		arg.ID,
		arg.RequirementID,
		arg.OldVersion,
		arg.NewVersion,
	)
	return err
}

const getAllChangeOrders = `-- name: GetAllChangeOrders :many
SELECT co.id, co.title, co.justification, co.effective_date, co.created_at,
       cos.status,
       u.full_name  AS assigned_to_name,
       cr.title     AS ecr_title
FROM change_orders co
JOIN change_order_statuses cos ON co.status_id  = cos.id
JOIN users                 u   ON co.assigned_to = u.id
JOIN change_requests       cr  ON co.ecr_id      = cr.id
ORDER BY co.created_at DESC
`

type GetAllChangeOrdersRow struct {
	ID             pgtype.UUID
	Title          string
	Justification  pgtype.Text
	EffectiveDate  pgtype.Date
	CreatedAt      pgtype.Timestamp
	Status         string
	AssignedToName string
	EcrTitle       string
}

func (q *Queries) GetAllChangeOrders(ctx context.Context) ([]GetAllChangeOrdersRow, error) {
	rows, err := q.db.Query(ctx, getAllChangeOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllChangeOrdersRow
	for rows.Next() {
		var i GetAllChangeOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Justification,
			&i.EffectiveDate,
			&i.CreatedAt,
			&i.Status,
			&i.AssignedToName,
			&i.EcrTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChangeOrderById = `-- name: GetChangeOrderById :one
SELECT co.id, co.title, co.justification, co.effective_date, co.created_at,
       cos.status,
       u.full_name AS assigned_to_name,
       cr.title    AS ecr_title
FROM change_orders co
JOIN change_order_statuses cos ON co.status_id  = cos.id
JOIN users                 u   ON co.assigned_to = u.id
JOIN change_requests       cr  ON co.ecr_id      = cr.id
WHERE co.id = $1
`

type GetChangeOrderByIdRow struct {
	ID             pgtype.UUID
	Title          string
	Justification  pgtype.Text
	EffectiveDate  pgtype.Date
	CreatedAt      pgtype.Timestamp
	Status         string
	AssignedToName string
	EcrTitle       string
}

func (q *Queries) GetChangeOrderById(ctx context.Context, id pgtype.UUID) (GetChangeOrderByIdRow, error) {
	row := q.db.QueryRow(ctx, getChangeOrderById, id)
	var i GetChangeOrderByIdRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Justification,
		&i.EffectiveDate,
		&i.CreatedAt,
		&i.Status,
		&i.AssignedToName,
		&i.EcrTitle,
	)
	return i, err
}

const updateChangeOrderStatus = `-- name: UpdateChangeOrderStatus :one
UPDATE change_orders co
SET co.status_id = (SELECT id FROM change_order_statuses WHERE status = $2)
WHERE co.id = $1
RETURNING id, ecr_id, title, justification, assigned_to, status_id, effective_date, created_at
`

type UpdateChangeOrderStatusParams struct {
	ID     pgtype.UUID
	Status string
}

func (q *Queries) UpdateChangeOrderStatus(ctx context.Context, arg UpdateChangeOrderStatusParams) (ChangeOrder, error) {
	row := q.db.QueryRow(ctx, updateChangeOrderStatus, arg.ID, arg.Status)
	var i ChangeOrder
	err := row.Scan(
		&i.ID,
		&i.EcrID,
		&i.Title,
		&i.Justification,
		&i.AssignedTo,
		&i.StatusID,
		&i.EffectiveDate,
		&i.CreatedAt,
	)
	return i, err
}
