// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAllDocuments = `-- name: GetAllDocuments :many
SELECT d.id, d.version_number, d.external_ref, d.title, d.description,
       d.is_external, d.file_path, d.uploaded_at,
       dt.type_code,
       ds.status,
       u.full_name AS uploaded_by_name
FROM documents d
JOIN document_types   dt ON d.type_id     = dt.id
JOIN document_statuses ds ON d.status_id  = ds.id
JOIN users             u  ON d.uploaded_by = u.id
ORDER BY d.uploaded_at DESC
`

type GetAllDocumentsRow struct {
	ID             pgtype.UUID
	VersionNumber  int32
	ExternalRef    pgtype.Text
	Title          string
	Description    pgtype.Text
	IsExternal     pgtype.Bool
	FilePath       pgtype.Text
	UploadedAt     pgtype.Timestamp
	TypeCode       string
	Status         string
	UploadedByName string
}

func (q *Queries) GetAllDocuments(ctx context.Context) ([]GetAllDocumentsRow, error) {
	rows, err := q.db.Query(ctx, getAllDocuments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllDocumentsRow
	for rows.Next() {
		var i GetAllDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.VersionNumber,
			&i.ExternalRef,
			&i.Title,
			&i.Description,
			&i.IsExternal,
			&i.FilePath,
			&i.UploadedAt,
			&i.TypeCode,
			&i.Status,
			&i.UploadedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDocumentById = `-- name: GetDocumentById :many
SELECT d.id, d.version_number, d.external_ref, d.title, d.description,
       d.is_external, d.file_path, d.uploaded_at,
       dt.type_code,
       ds.status,
       u.full_name AS uploaded_by_name
FROM documents d
JOIN document_types    dt ON d.type_id     = dt.id
JOIN document_statuses ds ON d.status_id  = ds.id
JOIN users              u  ON d.uploaded_by = u.id
WHERE d.id = $1
ORDER BY d.version_number
`

type GetDocumentByIdRow struct {
	ID             pgtype.UUID
	VersionNumber  int32
	ExternalRef    pgtype.Text
	Title          string
	Description    pgtype.Text
	IsExternal     pgtype.Bool
	FilePath       pgtype.Text
	UploadedAt     pgtype.Timestamp
	TypeCode       string
	Status         string
	UploadedByName string
}

func (q *Queries) GetDocumentById(ctx context.Context, id pgtype.UUID) ([]GetDocumentByIdRow, error) {
	rows, err := q.db.Query(ctx, getDocumentById, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDocumentByIdRow
	for rows.Next() {
		var i GetDocumentByIdRow
		if err := rows.Scan(
			&i.ID,
			&i.VersionNumber,
			&i.ExternalRef,
			&i.Title,
			&i.Description,
			&i.IsExternal,
			&i.FilePath,
			&i.UploadedAt,
			&i.TypeCode,
			&i.Status,
			&i.UploadedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
