// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Approval struct {
	ID            uuid.UUID
	RequirementID uuid.UUID
	VersionNumber int32
	StatusID      uuid.UUID
	Comment       sql.NullString
	RequestedAt   time.Time
	RespondedAt   sql.NullTime
}

type ApprovalStatus struct {
	ID        uuid.UUID
	Status    string
	CreatedAt time.Time
}

type ChangeOrder struct {
	ID            uuid.UUID
	EcrID         uuid.UUID
	Title         string
	Justification sql.NullString
	AssignedTo    uuid.UUID
	StatusID      uuid.UUID
	EffectiveDate sql.NullTime
	CreatedAt     time.Time
}

type ChangeOrderStatus struct {
	ID        uuid.UUID
	Status    string
	CreatedAt time.Time
}

type ChangeRequest struct {
	ID          uuid.UUID
	Title       string
	Description sql.NullString
	RequesterID uuid.UUID
	ProjectID   uuid.UUID
	StatusID    uuid.UUID
	PriorityID  uuid.UUID
	CreatedAt   time.Time
	ResolvedAt  sql.NullTime
}

type ChangeRequestPriority struct {
	ID        uuid.UUID
	Priority  string
	CreatedAt time.Time
}

type ChangeRequestRequirement struct {
	ID            uuid.UUID
	RequirementID uuid.UUID
	VersionNumber int32
}

type ChangeRequestStatus struct {
	ID        uuid.UUID
	Status    string
	CreatedAt time.Time
}

type Document struct {
	ID            uuid.UUID
	ExternalRef   sql.NullString
	Title         string
	Description   sql.NullString
	TypeID        uuid.UUID
	IsExternal    sql.NullBool
	VersionNumber int32
	FilePath      sql.NullString
	UploadedBy    uuid.UUID
	UploadedAt    time.Time
	StatusID      uuid.UUID
}

type DocumentProject struct {
	ID              uuid.UUID
	DocumentVersion int32
	ProjectID       uuid.UUID
}

type DocumentStatus struct {
	ID        uuid.UUID
	Status    string
	CreatedAt time.Time
}

type DocumentType struct {
	ID        uuid.UUID
	TypeCode  string
	CreatedAt time.Time
}

type EcoRequirementLink struct {
	ID            uuid.UUID
	RequirementID uuid.UUID
	OldVersion    int32
	NewVersion    int32
}

type Project struct {
	ID        uuid.UUID
	Name      string
	StartDate sql.NullTime
	EndDate   sql.NullTime
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Requirement struct {
	ID                    uuid.UUID
	ExternalID            sql.NullString
	ProjectID             uuid.UUID
	TypeID                uuid.UUID
	ParentVersion         sql.NullInt32
	CreatedBy             uuid.UUID
	CreatedAt             time.Time
	VersionNumber         int32
	Title                 string
	Description           sql.NullString
	SourceDocumentID      uuid.NullUUID
	SourceDocumentVersion sql.NullInt32
	SourceClause          sql.NullString
	StatusID              uuid.UUID
	IsBaseline            sql.NullBool
	ChangeReason          sql.NullString
	ChangedBy             uuid.UUID
	ChangedAt             time.Time
}

type RequirementStatus struct {
	ID        uuid.UUID
	Status    string
	CreatedAt time.Time
}

type RequirementType struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
}

type User struct {
	ID           uuid.UUID
	PasswordHash string
	FullName     string
	Email        string
	Department   sql.NullString
	Position     sql.NullString
	IsSupervisor bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
