// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Approval struct {
	ID            pgtype.UUID
	RequirementID pgtype.UUID
	VersionNumber int32
	StatusID      pgtype.UUID
	Comment       pgtype.Text
	ApproverID    pgtype.UUID
	CreatedAt     pgtype.Timestamp
}

type ApprovalStatus struct {
	ID        pgtype.UUID
	Status    string
	CreatedAt pgtype.Timestamp
}

type ChangeOrder struct {
	ID            pgtype.UUID
	EcrID         pgtype.UUID
	Title         string
	Justification pgtype.Text
	AssignedTo    pgtype.UUID
	StatusID      pgtype.UUID
	EffectiveDate pgtype.Date
	CreatedAt     pgtype.Timestamp
}

type ChangeOrderStatus struct {
	ID        pgtype.UUID
	Status    string
	CreatedAt pgtype.Timestamp
}

type ChangeRequest struct {
	ID          pgtype.UUID
	Title       string
	Description pgtype.Text
	RequesterID pgtype.UUID
	ProjectID   pgtype.UUID
	StatusID    pgtype.UUID
	PriorityID  pgtype.UUID
	CreatedAt   pgtype.Timestamp
	ResolvedAt  pgtype.Timestamp
}

type ChangeRequestPriority struct {
	ID        pgtype.UUID
	Priority  string
	CreatedAt pgtype.Timestamp
}

type ChangeRequestRequirement struct {
	ID            pgtype.UUID
	RequirementID pgtype.UUID
	VersionNumber int32
}

type ChangeRequestStatus struct {
	ID        pgtype.UUID
	Status    string
	CreatedAt pgtype.Timestamp
}

type Document struct {
	ID            pgtype.UUID
	ExternalRef   pgtype.Text
	Title         string
	Description   pgtype.Text
	TypeID        pgtype.UUID
	IsExternal    pgtype.Bool
	VersionNumber int32
	FilePath      pgtype.Text
	UploadedBy    pgtype.UUID
	UploadedAt    pgtype.Timestamp
	StatusID      pgtype.UUID
}

type DocumentProject struct {
	ID              pgtype.UUID
	DocumentVersion int32
	ProjectID       pgtype.UUID
}

type DocumentStatus struct {
	ID        pgtype.UUID
	Status    string
	CreatedAt pgtype.Timestamp
}

type DocumentType struct {
	ID        pgtype.UUID
	TypeCode  string
	CreatedAt pgtype.Timestamp
}

type EcoRequirementLink struct {
	ID            pgtype.UUID
	RequirementID pgtype.UUID
	OldVersion    int32
	NewVersion    int32
}

type Project struct {
	ID        pgtype.UUID
	Name      string
	StartDate pgtype.Date
	EndDate   pgtype.Date
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Requirement struct {
	ID                    pgtype.UUID
	ExternalID            pgtype.Text
	ProjectID             pgtype.UUID
	TypeID                pgtype.UUID
	ParentVersion         pgtype.Int4
	CreatedBy             pgtype.UUID
	CreatedAt             pgtype.Timestamp
	VersionNumber         int32
	Title                 string
	Description           pgtype.Text
	SourceDocumentID      pgtype.UUID
	SourceDocumentVersion pgtype.Int4
	SourceClause          pgtype.Text
	StatusID              pgtype.UUID
	IsBaseline            pgtype.Bool
	ChangeReason          pgtype.Text
	ChangedBy             pgtype.UUID
	ChangedAt             pgtype.Timestamp
}

type RequirementStatus struct {
	ID        pgtype.UUID
	Status    string
	CreatedAt pgtype.Timestamp
}

type RequirementType struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamp
}

type User struct {
	ID           pgtype.UUID
	PasswordHash string
	FullName     string
	Email        string
	Department   pgtype.Text
	Position     pgtype.Text
	IsSupervisor bool
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}
