// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (name, start_date)
VALUES ($1, $2)
RETURNING id, name, start_date, end_date, created_at, updated_at
`

type CreateProjectParams struct {
	Name      string
	StartDate sql.NullTime
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject, arg.Name, arg.StartDate)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProjectById = `-- name: UpdateProjectById :one
UPDATE projects
SET name = $1, start_date = $2, end_date = $3, updated_at = CURRENT_TIMESTAMP
WHERE id = $4
RETURNING id, name, start_date, end_date, created_at, updated_at
`

type UpdateProjectByIdParams struct {
	Name      string
	StartDate sql.NullTime
	EndDate   sql.NullTime
	ID        uuid.UUID
}

func (q *Queries) UpdateProjectById(ctx context.Context, arg UpdateProjectByIdParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, updateProjectById,
		arg.Name,
		arg.StartDate,
		arg.EndDate,
		arg.ID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
