// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: requirement.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAllRequirementVersions = `-- name: GetAllRequirementVersions :many
SELECT 
    r.id,
    r.external_id,
    rt.name AS type,
    parent.version_number AS parent_version,
    creator.full_name AS created_by,
    r.created_at,
    r.version_number,
    r.title,
    r.description,
    d.title AS source_document_name,
    COALESCE(r.source_document_version, d.version_number) AS source_document_version,
    r.source_clause,
    rs.status AS status,
    r.is_baseline,
    r.change_reason,
    changer.full_name AS changed_by,
    r.changed_at
FROM requirements r
LEFT JOIN users creator ON r.created_by = creator.id
LEFT JOIN users changer ON r.changed_by = changer.id
LEFT JOIN requirement_types rt ON r.type_id = rt.id
LEFT JOIN requirement_statuses rs ON r.status_id = rs.id
LEFT JOIN documents d ON r.source_document_id = d.id
LEFT JOIN requirements parent ON r.parent_id = parent.id
WHERE r.id = $1
ORDER BY r.version_number
`

type GetAllRequirementVersionsRow struct {
	ID                    pgtype.UUID
	ExternalID            pgtype.Text
	Type                  pgtype.Text
	ParentVersion         pgtype.Int4
	CreatedBy             pgtype.Text
	CreatedAt             pgtype.Timestamp
	VersionNumber         int32
	Title                 string
	Description           pgtype.Text
	SourceDocumentName    pgtype.Text
	SourceDocumentVersion int32
	SourceClause          pgtype.Text
	Status                pgtype.Text
	IsBaseline            pgtype.Bool
	ChangeReason          pgtype.Text
	ChangedBy             pgtype.Text
	ChangedAt             pgtype.Timestamp
}

func (q *Queries) GetAllRequirementVersions(ctx context.Context, id pgtype.UUID) ([]GetAllRequirementVersionsRow, error) {
	rows, err := q.db.Query(ctx, getAllRequirementVersions, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllRequirementVersionsRow
	for rows.Next() {
		var i GetAllRequirementVersionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Type,
			&i.ParentVersion,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.VersionNumber,
			&i.Title,
			&i.Description,
			&i.SourceDocumentName,
			&i.SourceDocumentVersion,
			&i.SourceClause,
			&i.Status,
			&i.IsBaseline,
			&i.ChangeReason,
			&i.ChangedBy,
			&i.ChangedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllRequirements = `-- name: GetAllRequirements :many
SELECT 
    r.id,
    r.external_id,
    rt.name AS type,
    parent.version_number AS parent_version,
    creator.full_name AS created_by,
    r.created_at,
    r.version_number,
    r.title,
    r.description,
    d.title AS source_document_name,
    COALESCE(r.source_document_version, d.version_number) AS source_document_version,
    r.source_clause,
    rs.status AS status,
    r.is_baseline,
    r.change_reason,
    changer.full_name AS changed_by,
    r.changed_at
FROM requirements r
LEFT JOIN users creator ON r.created_by = creator.id
LEFT JOIN users changer ON r.changed_by = changer.id
LEFT JOIN requirement_types rt ON r.type_id = rt.id
LEFT JOIN requirement_statuses rs ON r.status_id = rs.id
LEFT JOIN documents d ON r.source_document_id = d.id
LEFT JOIN requirements parent ON r.parent_id = parent.id
`

type GetAllRequirementsRow struct {
	ID                    pgtype.UUID
	ExternalID            pgtype.Text
	Type                  pgtype.Text
	ParentVersion         pgtype.Int4
	CreatedBy             pgtype.Text
	CreatedAt             pgtype.Timestamp
	VersionNumber         int32
	Title                 string
	Description           pgtype.Text
	SourceDocumentName    pgtype.Text
	SourceDocumentVersion int32
	SourceClause          pgtype.Text
	Status                pgtype.Text
	IsBaseline            pgtype.Bool
	ChangeReason          pgtype.Text
	ChangedBy             pgtype.Text
	ChangedAt             pgtype.Timestamp
}

func (q *Queries) GetAllRequirements(ctx context.Context) ([]GetAllRequirementsRow, error) {
	rows, err := q.db.Query(ctx, getAllRequirements)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllRequirementsRow
	for rows.Next() {
		var i GetAllRequirementsRow
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Type,
			&i.ParentVersion,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.VersionNumber,
			&i.Title,
			&i.Description,
			&i.SourceDocumentName,
			&i.SourceDocumentVersion,
			&i.SourceClause,
			&i.Status,
			&i.IsBaseline,
			&i.ChangeReason,
			&i.ChangedBy,
			&i.ChangedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRequirementsByProjectId = `-- name: GetRequirementsByProjectId :many
SELECT 
    r.id,
    r.external_id,
    rt.name AS type,
    parent.version_number AS parent_version,
    creator.full_name AS created_by,
    r.created_at,
    r.version_number,
    r.title,
    r.description,
    d.title AS source_document_name,
    COALESCE(r.source_document_version, d.version_number) AS source_document_version,
    r.source_clause,
    rs.status AS status,
    r.is_baseline,
    r.change_reason,
    changer.full_name AS changed_by,
    r.changed_at
FROM requirements r
LEFT JOIN users creator ON r.created_by = creator.id
LEFT JOIN users changer ON r.changed_by = changer.id
LEFT JOIN requirement_types rt ON r.type_id = rt.id
LEFT JOIN requirement_statuses rs ON r.status_id = rs.id
LEFT JOIN documents d ON r.source_document_id = d.id
LEFT JOIN requirements parent ON r.parent_id = parent.id
WHERE r.project_id = $1
ORDER BY r.created_at, r.version_number DESC
`

type GetRequirementsByProjectIdRow struct {
	ID                    pgtype.UUID
	ExternalID            pgtype.Text
	Type                  pgtype.Text
	ParentVersion         pgtype.Int4
	CreatedBy             pgtype.Text
	CreatedAt             pgtype.Timestamp
	VersionNumber         int32
	Title                 string
	Description           pgtype.Text
	SourceDocumentName    pgtype.Text
	SourceDocumentVersion int32
	SourceClause          pgtype.Text
	Status                pgtype.Text
	IsBaseline            pgtype.Bool
	ChangeReason          pgtype.Text
	ChangedBy             pgtype.Text
	ChangedAt             pgtype.Timestamp
}

func (q *Queries) GetRequirementsByProjectId(ctx context.Context, projectID pgtype.UUID) ([]GetRequirementsByProjectIdRow, error) {
	rows, err := q.db.Query(ctx, getRequirementsByProjectId, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRequirementsByProjectIdRow
	for rows.Next() {
		var i GetRequirementsByProjectIdRow
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.Type,
			&i.ParentVersion,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.VersionNumber,
			&i.Title,
			&i.Description,
			&i.SourceDocumentName,
			&i.SourceDocumentVersion,
			&i.SourceClause,
			&i.Status,
			&i.IsBaseline,
			&i.ChangeReason,
			&i.ChangedBy,
			&i.ChangedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
