// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (password_hash, full_name, email, department, position, is_supervisor)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, password_hash, full_name, email, department, position, is_supervisor, created_at, updated_at
`

type CreateUserParams struct {
	PasswordHash string
	FullName     string
	Email        string
	Department   pgtype.Text
	Position     pgtype.Text
	IsSupervisor bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.PasswordHash,
		arg.FullName,
		arg.Email,
		arg.Department,
		arg.Position,
		arg.IsSupervisor,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PasswordHash,
		&i.FullName,
		&i.Email,
		&i.Department,
		&i.Position,
		&i.IsSupervisor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    password_hash = COALESCE($1, password_hash),
    full_name     = COALESCE($2,     full_name),
    email         = COALESCE($3,         email),
    department    = COALESCE($4,    department),
    position      = COALESCE($5,      position),
    is_supervisor = COALESCE($6, is_supervisor),
    updated_at    = CURRENT_TIMESTAMP
WHERE id = $7
RETURNING id, password_hash, full_name, email, department, position, is_supervisor, created_at, updated_at
`

type UpdateUserParams struct {
	PasswordHash pgtype.Text
	FullName     pgtype.Text
	Email        pgtype.Text
	Department   pgtype.Text
	Position     pgtype.Text
	IsSupervisor pgtype.Bool
	ID           pgtype.UUID
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.PasswordHash,
		arg.FullName,
		arg.Email,
		arg.Department,
		arg.Position,
		arg.IsSupervisor,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PasswordHash,
		&i.FullName,
		&i.Email,
		&i.Department,
		&i.Position,
		&i.IsSupervisor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
